### ISSUE TITLE
Automatically insert license headers in new files does not work

### ISSUE THREAD

**Issue by alex7egli** [rubicon-oss/LicenseHeaderManager#56]
I am using Visual Studio 2015 Community Edition on Windows 10. In my project settings I have checked the box "Automatically insert license headers in new files", and configured my licenseheader file to add a header for .js files. When I create a new .js file in the project though there is no license header in it.

This is the projectname.licenseheader file:
extensions: .js
//
//////////////////////////////////////////////////////////////
// C O P Y R I G H T (c) 2014                               //
// Company Name. and/or its affiliates         //
// All Rights Reserved                                      //
//////////////////////////////////////////////////////////////
//                                                          //
// The copyright notice above does not evidence any         //
// actual or intended publication of such source code.      //
//                                                          //
//////////////////////////////////////////////////////////////
//

**Comment by FlorianDecker** [comment]
Hi alex7egli!

Thanks for the issue report!

Sadly i could not reproduce the problem consistently. While it didn't add the Licenseheader the first time i tried it, as soon as i went to debug it, it worked everytime flawlessly. I have yet to find a way to reset it to a state where it does not work. 

Just to exclude a possible misconfiguration, does adding the Licenseheader normally with the LicenseheaderManager work after you added the file? (Rightclick on File -> License Headers -> Add License Header)

Does this problem happen in only one Project or can you reproduce it with a newly created Projekt?

Thanks for your help!

**Comment by alex7egli** [comment]
I can consistently reproduce the issue. I tried with another project and the same thing happened. Steps I took to create project and use license headers:
1) In Visual Studio 2015 Community Edition click File > New > Web Site
2) Leave ASP.NET Empty Web Site selected
3) For Web Location browse to folder of existing project that was created with WebStorm
4) Click OK. At the prompt choose to use existing web project.
5) Right click Project name in solution exploring, go to License Headers > Add New License Header Definition File
6) Fill in the license header file with my content above and save and close it
7) Right click Project name in solution exploring, go to License Headers > Options
8) Select "Automatically insert license headers in new files" and click Save
9) On any folder in the project right click and create new Javascript file
EXPECTED: javascript file created with license header at top
ACTUAL: empty javascript file created

**Comment by FlorianDecker** [comment]
Thanks for the detailed instructions, i was able to reproduce it! 

This is an error due to the project type "Website" having its own set of events and not firing the standard "ItemAdded" event.
 
This is should be a relative easy fix (just have to test it thoroughly, as this post https://social.msdn.microsoft.com/Forums/en-US/dde7d858-2440-43f9-bbdc-3e1b815d4d1e/itemadded-itemremoved-and-itemrenamed-events-not-firing-in-web-projects?forum=vsx suggests that the EventHandler fires on unexpected occasions).

If it passes our manual tests, we are going to include the fix with our next service release (currently planned for december).

As a temporary workaround, you could configure the LicenseHeaderManager to update the LicenseHeader everytime you save the file.

To do so:
Tools -> Options -> License Header Manager -> Add... -> File.SaveSelectedItems -> OK. 

Or, if you want this fix now (untested), you can download the branch with the fix (https://github.com/rubicon-oss/LicenseHeaderManager/tree/bugfix/issue-56_website_add_licenseheader_to_new_created_item_does_not_work), compile the Solution and install the resulting .vsix manually (you may have to uninstall the current Version first).

**Comment by alex7egli** [comment]
Thanks for the quick response! I don't mind waiting till december. I'll manually add the header until then.

**Comment by FlorianDecker** [comment]
Hi!

Just as information, we are postponing our next release to January next year, as we also want to include Visual Studio 2017 support. 

Sorry for the delay!
