### ISSUE TITLE
Is it possible to provide licenseheader file at a solution level.

### ISSUE THREAD

**Issue by ukanase** [rubicon-oss/LicenseHeaderManager#58]
I have 100+ projects in my VS solution and in all the files I want to include the same header. It will be good if license header configuration can be specified at a solution level. 

The option "Add License Headers to All The Projects" is not working and it took lot of time in my sample application with 2 projects and finally VS got hanged.

**Comment by MichaelKetting** [comment]
Hi ukanase!

Not sure at the moment if the solution level option has been discussed before. Will need to dig through the open feature requests for this. Since we already support hierarchical license header files inside the project and its folders, it would seem like the next logical step. 

It could be, that Visual Studio itself disagrees, though. That will need to be checked.

In the mean time: I've solved this by adding linked license header files. The link can also be copied between projects, so it's just CTRL+V 100+ times to solve this with the exisitng infrastructure. And for the record: it's what we did in our 100+ project solutions, too :)

Best regards, Michael

**Comment by FlorianDecker** [comment]
Hi!

On a quick glance i could not find an open feature request for solution level .licenseheader files. A solution level licenseheader file would have to be added in a solution folder, which would somehow bite itself with #54 . So i think a single .licenseheader file somewhere in a solution folder being used for all other Projekts in the solution would not be intuitive.
(So not like this)
![grafik](https://cloud.githubusercontent.com/assets/13847286/21097810/a7f8049c-c066-11e6-9980-2d5612f3330e.png)


But what we could easily define would be considering .licenseheader files when they are together with Projects in the same Solution Folder (which sadly does not work at the moment).
![grafik](https://cloud.githubusercontent.com/assets/13847286/21097820/b6de6f46-c066-11e6-9e44-68f846aa98fb.png)

If you already group your Projects in SolutionFolders, you would only have to add one .licenseheader File per Solution Folder, which would mean less Ctrl + V. This should work like hierarchies inside a project, so that the .licenseheader file closest to the source file would be applied.

Maybe we could also add a context menu to the Solution Item, like "Add existing License Header Definition File to all Solution Folders" or similar.

Regarding VS hanging, could you open a seperate issue with a link to the sample application and the steps to reproduce the error? I cant reproduce it locally but would really like kill any errors which lead to VS hanging.

Best Regards,
Florian

**Comment by RandomEngy** [comment]
I would add code to detect the solution-level license header automatically. Something like `Path.GetDirectory(DTE2.Solution.FullName)`, then search for .licenseheader files beside it. Or pull a Resharper and name it MySolution.sln.licenseheader . Then you could detect it and use it as a fallback if you didn't have one in a project.

**Comment by FlorianDecker** [comment]
Added in 2.0.3 by @RandomEngy . Thanks!
