### ISSUE TITLE
Git Expendable Properties

### ISSUE THREAD

**Issue by felaugmar** [rubicon-oss/LicenseHeaderManager#98]
There is a way to get information from the git's repository the project is on?
Some Expendable Properties could be get from there, like these:

- Git's file creation date;
- Git's first user that commited that file;
- Git's last user that commited that file;
- Git's project name.
- Git's project description.
- Git's project license.
- etc.

I found issues for that in #26 and #27, but the last update on both was on 2016.

**Comment by MichaelKetting** [comment]
Well, some things like project name, description, and license are not Git sepecific but Github specific. As for the rest, the same constraints apply as they do for #26 and #27. If it's exposed out of the box, it would be an interesting option for contribution. If it would rely on a 3rd party dependency on Git or Github, it's most likely a can of worms in regards to maintaining it / keeping it up to date. 

In #26, there was discussion about about allowing the call to an executable when evaluating the placeholder which could solve the Git and/or Github dependency. Syntax aside, It does bring with it security implications because you would execute code defined by someone else on your development machine just by editing/formatting a file and unrelated, there's also the performance aspect to consider.

I would say, first step would be to determine if and what Visual Studios VSC APIs can supply out of the box.
